language: c

os:
  - linux
  - osx

before_script:
  - git clone --branch master --depth=1 https://github.com/asdf-vm/asdf.git asdf
  - source asdf/asdf.sh

script:
  - asdf plugin-test k9s $TRAVIS_BUILD_DIR --asdf-tool-version 0.12.0
  - asdf plugin-test k9s $TRAVIS_BUILD_DIR --asdf-tool-version v0.13.0
  - asdf plugin-test k9s $TRAVIS_BUILD_DIR --asdf-tool-version v0.14.0
