name: Main Workflow

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: "0 0 * * 5"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test_latest
        uses: asdf-vm/actions/plugin-test@v1.0.1
        with:
          command: k9s help
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # these tests to cover when the naming convention of the download files changed

      - name: asdf_plugin_test_0_12_0
        uses: asdf-vm/actions/plugin-test@v1.0.1
        with:
          command: k9s help
          version: "0.12.0"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: asdf_plugin_test_0_13_0
        uses: asdf-vm/actions/plugin-test@v1.0.1
        with:
          command: k9s help
          version: "v0.13.0"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: asdf_plugin_test_0_14_0
        uses: asdf-vm/actions/plugin-test@v1.0.1
        with:
          command: k9s help
          version: "v0.14.0"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
